### ISSUE TITLE
Vault not found on iOS

### ISSUE THREAD

**Issue by kometenstaub** [mhbl3/obsidian-pdf-gen#3]
Wegen I execute the PDF generation from the share sheet on iOS (after having used the pickVault shortcut), it does not find the vault. 

I set the vault again multiple times, but still no luck. 
It is located “on my iPhone” and not in iCloud. 

```sh
jump: MHBL Vault not found.
WARNING:ObiPdfGen:File 'obsidian mobile switc
her.md' not found, trying to find it...
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Applicati
on/AC3DA01D-2D4C-4F83-AA93-6F3AC1ED2CF7/Libra
ry/lib/python3.11/site-packages/obsidian_pdf_
gen/generate_pdf/md_notes_pdf.py", line 193, 
in add_note
    with open(note_path, "r", encoding="utf-8
") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^
FileNotFoundError: [Errno 2] No such file or 
directory: 'obsidian mobile switcher.md'
During handling of the above exception, anoth
er exception occurred:
Traceback (most recent call last):
  File "/var/mobile/Containers/Data/Applicati
on/AC3DA01D-2D4C-4F83-AA93-6F3AC1ED2CF7/Libra
ry/bin/obsi_pdf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/mobile/Containers/Data/Applicati
on/AC3DA01D-2D4C-4F83-AA93-6F3AC1ED2CF7/Libra
ry/lib/python3.11/site-packages/obsidian_pdf_
gen/generate_pdf/md_notes_pdf.py", line 1120,
 in main
    tex.add_note(args.note, note_path, use_ch
apters, include_linked_notes)
  File "/var/mobile/Containers/Data/Applicati
on/AC3DA01D-2D4C-4F83-AA93-6F3AC1ED2CF7/Libra
ry/lib/python3.11/site-packages/obsidian_pdf_
gen/generate_pdf/md_notes_pdf.py", line 205, 
in add_note
    raise FileNotFoundError(
FileNotFoundError: File 'obsidian mobile swit
cher.md' not found in current directory and s
ubdirectories
[~group]$ 

```

iOS 16.4.1 (20E252), security response is installed

**Comment by mhbl3** [comment]
Thanks for using the tool and helping making it better!
Could try to change the content of this shortcuts to the name of your vault (the one you just pickFolder)?
![image](https://github.com/mhbl3/obsidian-pdf-gen/assets/19601137/c90221db-c95b-4372-a05e-a2b16d8f710e)

Alternatively, I have added the setup of name of one's vault in the [Generate Obsidian Note PDF shortcut](https://www.icloud.com/shortcuts/a28954ec37c34e778f6047912761983f)

**Comment by kometenstaub** [comment]
Thank you!

At first, it prompted me to download `pdflatex`, which I did, and subsequently it crashed multiple times and told me that it couldn't find the file I tried to export, but then it did work at some point. I only noticed it accidentally, since it had saved the log files and the PDF in my vault root. 

I tried a bit later now (and assume that the `pdflatex` download worked), and now the export works. One issue is that footnotes don't preserve whitespace (all is one big word, and they're not put into the footer).

**Comment by mhbl3** [comment]
Hmm the crashing might be due to too much printing to the A-shell terminal. I need to take another stab at reducing it! 

Could you provide an example of the footnote? I don't use them so probably don't handle them properly!

**Comment by kometenstaub** [comment]
Image of the PDF:

![image](https://github.com/mhbl3/obsidian-pdf-gen/assets/83140328/c68e8666-744d-4f6f-b3ce-395aaee90889)

Content of the Markdown file:

```md
---
created: 2023-05-19 17:50
parent:
- 
aliases: null
tags: null
publish: false
---



Hello, this is a test with a footnote.[^1]

[^1]: See this footnote.
```

How it looks in reading mode in Obsidian:

![image](https://github.com/mhbl3/obsidian-pdf-gen/assets/83140328/d4012afd-0a28-428f-9576-eac6f1ed271d)

**Comment by mhbl3** [comment]
Thanks a lot for all the info, I really appreciate it!

**Comment by kometenstaub** [comment]
Thank you for looking into it!

**Comment by mhbl3** [comment]
The footnote issue should be fixed in `v1.7.1`. See an example [here](https://github.com/mhbl3/obsidian-pdf-gen/blob/1.7.x/tests/test_files/footnotes.pdf). 

Try upgrading in a-shell using `pip install obsidian-pdf-gen==1.7.1` and give it a shot!

**Comment by kometenstaub** [comment]
Thank you, I can confirm this works now. 

I do have one other question: How could I remove the red rectangles around the TOC headings and the footnote (so basically everything that is linked)?

**Comment by mhbl3** [comment]
That's a good point. I added a fix for that in my next code version `1.7.2`. Will release that later today

**Comment by mhbl3** [comment]
Should be on pypi now with `pip install obsidian-pdf-gen==1.7.2`

**Comment by kometenstaub** [comment]
Yes, I can confirm that the red rectangles are gone now. 
Thank you so much for your support and all the work you’ve put into this! :)
