### ISSUE TITLE
Heading level 6 does not work

### ISSUE THREAD

**Issue by kometenstaub** [mhbl3/obsidian-pdf-gen#6]
Heading level 6 does not work. I noticed it in a bigger note, but here is a minimal repro:

<img width="902" alt="image" src="https://github.com/mhbl3/obsidian-pdf-gen/assets/83140328/a3fdcef0-5238-4c8f-a891-2427639d54ab">

```md
---
created: 2023-05-21 22:38
parent:
- 
aliases: null
tags: null
publish: false
---

# level 1

This is a sentence.

## level 2

This is a sentence.

### level 3

This is a sentence.

#### level 4

This is a sentence.

##### level 5

This is a sentence.

###### level 6

This is a sentence.
```

---

Somewhat related:
1. Is it intended, that starting from level 4 everything gets indented?
2. Should the file name always be `1` in the table of contents?

<img width="962" alt="image" src="https://github.com/mhbl3/obsidian-pdf-gen/assets/83140328/d2cfb5bb-fe02-4fd2-bcf3-fcee2c06538b">

I think it would make more sense to put the file name at the top, then have `Contents` and use the H1 (or whatever is the biggest heading) as `1`, `2`, etc.

Although, considering the `use_chapters` flag, I guess this behaviour might make sense, especially in connection with the `iln` flag? For reference, the output with that flag set to `false` (although with some additional text).

<img width="1076" alt="image" src="https://github.com/mhbl3/obsidian-pdf-gen/assets/83140328/c2b2243f-578a-4f5d-b6b9-ac62a77b974c">

**Comment by mhbl3** [comment]
1. It's a "problem" with Latex. I need to customize those levels, using latex code, to look better. But I agree, I don't like the indent either
2. Yes, as you mentioned it was really so that each note is a chapter. May be the behavior sous be to default to `use_chapters=false` when only one more is lined linked?

**Comment by kometenstaub** [comment]
2. I suppose if it is only one note, it should default to use_chapters=false, unless explicitly overridden.

**Comment by mhbl3** [comment]
Hey just FYI: I haven't forgotten about this, I just have other stuff to handle before I get back to this!
